name: flutter_time_button
description: A new Flutter timer button widget.
version: 2.0.0
homepage: https://github.com/wendellrocha/time_button

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter